import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ModalContainer from "./components/modal/ModalContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="withNavbar"> {/* 글로벌 CSS에 .withNavbar { display: flex; } 추가 필요 */}
          <Navbar />
          <main className="mainContent"> {/* 글로벌 CSS에 .mainContent 스타일 추가 필요 */}

            {children}
          </main>
        </div>
        <ModalContainer />
      </body>
    </html>
  );
}